# Generated by Django 3.1.7 on 2021-03-02 10:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.FloatField(max_length=500)),
                ('account_status', models.CharField(default='active', max_length=10)),
                ('account_number', models.IntegerField(max_length=10)),
                ('account_pin', models.IntegerField(max_length=4)),
                ('date_created', models.DateField(default=datetime.date(2021, 3, 2))),
                ('date_updated', models.DateField(default=datetime.date(2021, 3, 2))),
            ],
        ),
        migrations.CreateModel(
            name='Overdraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdraft_amount', models.FloatField(max_length=500)),
                ('overdraft_balance', models.FloatField(max_length=500)),
                ('overdraft_status', models.CharField(default='active', max_length=20)),
                ('date_created', models.DateField(default=datetime.date(2021, 3, 2))),
                ('date_updated', models.DateField(default=datetime.date(2021, 3, 2))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AMSapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('date_created', models.DateField(default=datetime.date(2021, 3, 2))),
                ('date_updated', models.DateField(default=datetime.date(2021, 3, 2))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_balance', models.FloatField(max_length=500)),
                ('loan_status', models.CharField(default='active', max_length=20)),
                ('loan_type', models.CharField(max_length=20)),
                ('loan_amount', models.FloatField(max_length=500)),
                ('date_created', models.DateField(default=datetime.date(2021, 3, 2))),
                ('date_updated', models.DateField(default=datetime.date(2021, 3, 2))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AMSapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('date_created', models.DateField(default=datetime.date(2021, 3, 2))),
                ('date_updated', models.DateField(default=datetime.date(2021, 3, 2))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AMSapp.accountholder'),
        ),
    ]
