# Generated by Django 3.1.7 on 2021-03-03 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 3)),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 3)),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 3)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 3)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='overdraft',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 3)),
        ),
        migrations.AlterField(
            model_name='overdraft',
            name='date_updated',
            field=models.DateField(null=True),
        ),
    ]
