# Generated by Django 3.1.7 on 2021-03-09 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0002_auto_20210303_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default=None, max_length=75),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 9)),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 9)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 9)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 9)),
        ),
        migrations.AlterField(
            model_name='overdraft',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 9)),
        ),
    ]
