# Generated by Django 3.1.7 on 2021-03-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0003_auto_20210309_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_name',
        ),
    ]
