# Generated by Django 3.1.7 on 2021-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0004_remove_account_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='sex',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
