# Generated by Django 3.1.7 on 2021-03-10 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0005_accountholder_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 10)),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 10)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 10)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 10)),
        ),
        migrations.AlterField(
            model_name='overdraft',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 10)),
        ),
    ]
